### ISSUE TITLE
Question about GLUE dataset

### ISSUE THREAD

**Issue by qtyandhasee** [YouAreSpecialToMe/QST#5]
Hello! Thank you for your excellent code. In the paper, it is mentioned that fine-tuning was done on the GLUE dataset, but the load_data function in the code does not include GLUE. How can the results on the GLUE dataset be reproduced? Thank you very much!

**Comment by YouAreSpecialToMe** [comment]
Hi, you can use "QSTLlamaForSequenceClassification" or "QSTOPTForSequenceClassification"  and the huggingface GLUE dataset to test QST's performance.

**Comment by qtyandhasee** [comment]
> Hi, you can use "QSTLlamaForSequenceClassification" or "QSTOPTForSequenceClassification" and the huggingface GLUE dataset to test QST's performance.

Should I use the  file "qst.py" or https://github.com/huggingface/transformers/blob/main/examples/pytorch/text-classification/run_glue.py

**Comment by qtyandhasee** [comment]
Do you train on GLUE dataset？

**Comment by YouAreSpecialToMe** [comment]
Hi, I've uploaded the glue_qst.py to conduct experiments on the GLUE benchmark and you can run the glue_qsy.sh to run the script.

**Comment by qtyandhasee** [comment]
> Hi, I've uploaded the glue_qst.py to conduct experiments on the GLUE benchmark and you can run the glue_qsy.sh to run the script.

Thank you！

**Comment by Xingke-yang** [comment]
Can you successfully use this script to reproduce data results similar to those reported in the paper, on the OPT-1.3B model? Thanks @YouAreSpecialToMe @qtyandhasee
