### ISSUE TITLE
Error while training OPT model on mrpc GLUE.

### ISSUE THREAD

**Issue by Singla17** [YouAreSpecialToMe/QST#6]
Hi, Thanks for your great work. 
I am trying to train OPT-1.3B using your work and am running into a bit of an issue.

The HF model I am using is this: `facebook/opt-1.3b`

I am facing the error below:
`AttributeError: 'QSTOPTDecoder' object has no attribute 'blackbone'`

The code block where it fails is modelling_opt_qst.py (lines 1130 - 1139):
```python
        # check if head_mask has a correct number of layers specified if desired
        for attn_mask, mask_name in zip([head_mask], ["head_mask"]):
            if attn_mask is not None:
                if attn_mask.size()[0] != (len(self.blackbone)):
                    raise ValueError(
                        f"The `{mask_name}` should be specified for {len(self.blackbone)} layers, but it is for"
                        f" {head_mask.size()[0]}."
                    )

        qst_hidden_states = self.downsample[0](hidden_states)
        for idx, decoder_layer in enumerate(self.blackbone):
```

It'd be great if you could take a look.

**PS**: If I replace backbone here with backbone, I run into another error:

`RuntimeError: The size of tensor a (2048) must match the size of tensor b (128) at non-singleton dimension 2`

line 1192 in forward method of `QSTOPTDecoder`class

```python
z = torch.sigmoid(self.z[idx])
qst_hidden_states = (1 - z) * self.downsample[idx](hidden_states) + z * qst_hidden_states
```

Thanks!

**Comment by YouAreSpecialToMe** [comment]
Hi,

Thanks for informing me. I've updated the code on GitHub. Now it works fine
on my side using 2 A100 GPUs. Can you update the code and try again?

Best,
Zhengxin

**Comment by Singla17** [comment]
Thanks a lot for looking into this. 

It works now, though I had to make a couple more changes: 
1. Line 2041: `self.model = QSTOPTModel(llm.model, config, QSTConfig, llm.hf_device_map) `
2. Line 2044: `self.score_z = nn.Parameter(torch.zeros(config.config.hidden_size)).to(llm.score.weight.device)`

**Comment by YouAreSpecialToMe** [comment]
Thanks for your information!
